# This is a basic workflow to help you get started with Actions

name: delete-workflow-runs

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  perfowm:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Delete old workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.1.0
        id: delete-workflow-runs
        with:
          repository: JustDJplease/JustDJplease.github.io   # replace this with your own repository
          older-than-seconds: 86400                         # remove all workflow runs older than 1 day
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

